### ISSUE TITLE
Generating markup from nothing (!)

### ISSUE THREAD

**Issue by iparr** [RealFaviconGenerator/gulp-real-favicon#10]
I am using the `inject-favicon-markups` task as provided by this tool and described in the documentation.

My use-case is as follows:
I have Twig-powered CMS. This uses a series of template 'partials' to produce dynamic webpages.

I want to generate the recommended markup so I can include this as a 'partial' for consumption by the CMS. What I've done is create a blank `.html` file which this task uses as its `src` and the task will successfully output the Favicon markup.

Is there any way of using this so that I do not to create this file and instead it just outputs the relevant markup into a new file of my choosing?

I know this is probably 'small fry' but it'd really help me keep things clean and nice and tidy for the developers I am working with. Regardless, this is a wonderful little tool. So thanks.

Here is my Gulp config:

```
gulp.task('inject-favicon-markups', function() {
    gulp.src([ 'app/craft/templates/_partial/favicon-dummy.twig'])
        .pipe(realFavicon.injectFaviconMarkups(JSON.parse(fs.readFileSync(FAVICON_DATA_FILE)).favicon.html_code))
        .pipe(gulp.dest('app/craft/templates/_partial/favicon-dump/'));
});
```

**Comment by iparr** [comment]
Closing this, because it's unfair to call this a problem of this generator and is more a general Gulp issue.

My much cleaner solutions is as follows:

```
gulp.task('inject-favicon-markups', function() {
    require('fs').writeFileSync('app/craft/templates/_partial/favicons.twig', '');
    gulp.src([ 'app/craft/templates/_partial/favicons.twig'])
        .pipe(realFavicon.injectFaviconMarkups(JSON.parse(fs.readFileSync(FAVICON_DATA_FILE)).favicon.html_code))
        .pipe(gulp.dest('app/craft/templates/_partial/'));
}));
```

**Comment by dixhuit** [comment]
@iparr Thanks for this tip, just what I was looking to do also 😄 

Tiny edit required though as the above task causes Gulp to fail (one parenthesis too many on the last line). It should be:

```
gulp.task('inject-favicon-markups', function() {
    require('fs').writeFileSync('app/craft/templates/_partial/favicons.twig', '');
    gulp.src([ 'app/craft/templates/_partial/favicons.twig'])
        .pipe(realFavicon.injectFaviconMarkups(JSON.parse(fs.readFileSync(FAVICON_DATA_FILE)).favicon.html_code))
        .pipe(gulp.dest('app/craft/templates/_partial/'));
});
```
