### ISSUE TITLE
Error while running command (identify '/path/to/realfavicongenerator_web_site/realfavicongenerator/tmp/pics/realfaviconcreator_vector_guess_WeQjGi.svg'), error code is 1

### ISSUE THREAD

**Issue by pixeline** [RealFaviconGenerator/gulp-real-favicon#11]
I keep getting this error when running `gulp generate-favicon`, and cannot make sense of it. Can you advise?

```
> gulp generate-favicon
[21:20:03] Using gulpfile ~/GITHUB/this-project/gulpfile.js
[21:20:03] Starting 'generate-favicon'...

/Users/me/GITHUB/this-project/node_modules/gulp-real-favicon/index.js:24
        throw new gutil.PluginError({
        ^
Error: Error while running command (identify '/home/realfavicongenerator_web_site/realfavicongenerator/tmp/pics/realfaviconcreator_vector_guess_rltdyj.svg'), error code is 1
```

Thank you,
A.

**Comment by phbernard** [comment]
Thank you for reporting. What annoys me the most here is that you get a path related to the server, not the kind of information to disclose to the client.

Could you post the master image you are using? If you can't post it here (eg. if it's not PNG/JPG), you can mail it to me at contact@realfavicongenerator.net

**Comment by pixeline** [comment]
Here it is: it turns out the file is corrupted (probably caused by git or gulp). I'll see if recreating the image solves the issue.
![favicon-source](https://cloud.githubusercontent.com/assets/393415/19146973/386fc36a-8bb6-11e6-8cdf-8cd15c1272dd.png)

**Comment by pixeline** [comment]
Yes, it does. Now the task completes successfully.

**Comment by phbernard** [comment]
I see. Then I would says that everything happens as expected, except for the error message. I close this issue since the Gulp plugin just did the right thing and open https://github.com/RealFaviconGenerator/realfavicongenerator/issues/284
