### ISSUE TITLE
what are the default realFavicon.generateFavicon() parameters?

### ISSUE THREAD

**Issue by pryley** [RealFaviconGenerator/gulp-real-favicon#13]
More specifically, what are the default parameters for the following options?
```js
{
      design: {},
      settings: {},
      versioning: {},
}
```
Copy/pasting from the website results in a huge gulp task function, I want to only include the non-default parameters.

**Comment by phbernard** [comment]
Well, there are some defaults, and they could be reproduced here. However, and while what you suggest definitely makes sense, this is against RFG approach. Changing this would require non-trivial changes in RFG.

RFG approach is that you should not look at the generated code, unless this is really what you want. So if the code is too large, it should be moved in a separate file. As an alternative, if could be moved to a JSON file and loaded by the Gulp module.
