### ISSUE TITLE
debug dependency is a vulnerability

### ISSUE THREAD

**Issue by PrabhanshuAttri** [RealFaviconGenerator/gulp-real-favicon#19]
npm@6 reported `debug` as a potential security vulnerability.

![gulp-real-favicon](https://user-images.githubusercontent.com/4739486/39950806-c1d7ec2a-55a1-11e8-9a2f-a3a71cbb876f.png)

Please upgrade `debug` dependency to >=2.6.9.

**Comment by jkaeser** [comment]
@PrabhanshuAttri This is an issue with the node-rest-client package. There's an open PR to fix the issue here: https://github.com/aacerox/node-rest-client/pull/164

**Comment by phbernard** [comment]
Unfortunately this is in node-rest-client maintainer's hands, and this project seems to be no longer supported.

See also https://github.com/RealFaviconGenerator/rfg-api/issues/14

**Comment by PrabhanshuAttri** [comment]
@jkaeser @phbernard If node-rest-client is no longer support, then we should move to axios.

**Comment by phbernard** [comment]
[Done, to be published](https://github.com/RealFaviconGenerator/rfg-api/issues/14). No more vulnerabilities!

If you want to review the code, you have a few days to do so until it's published.

**Comment by phbernard** [comment]
gulp-real-favicon v0.3.1 was published a minute ago. No more vulnerabilities!
