### ISSUE TITLE
Update modifies source code

### ISSUE THREAD

**Issue by xf-** [RealFaviconGenerator/gulp-real-favicon#20]
After the latest update attributes in tags get an value and other issues.

e.g.
<tag required changes to <tag required="" and messes with other gulp tasks and destroys inline SVG images.

**Comment by MindSculpt** [comment]
+1 — this is breaking some inline SVGs. What's the status on a fix for this? Anyone? @xf- Which earlier version of the plugin is it not doing this?

**Comment by xf-** [comment]
fixed

**Comment by MindSculpt** [comment]
@xf Is there a new version or is the fix unrelated to the codebase?

**Comment by xf-** [comment]
@MindSculpt i think it was a dependency and a yarn upgrade fixes it for me
