### ISSUE TITLE
Specify start url

### ISSUE THREAD

**Issue by bjarnef** [RealFaviconGenerator/gulp-real-favicon#22]
How do I specify the `start_url` in the generated `site.webmanifest` e.g. used in Chrome?

![image](https://user-images.githubusercontent.com/2919859/51386228-fdf3e100-1b21-11e9-86a3-5314abb68602.png)

**Comment by pverhaert** [comment]
Just add **startUrl** to the manifest 
`manifest: {
    name: 'My App,
    startUrl: '/',
    display: 'standalone',
    ...
},`

**Comment by bjarnef** [comment]
Okay, I guess it just wasn't documented at the time of writing and not generated from here:
https://realfavicongenerator.net/favicon/gulp

Chrome is warning about missing `name`, `short_name`, `short_url` fields, but it seems only `name` is required:
https://developer.mozilla.org/en-US/docs/Web/Manifest/name
